# Generated by codegen/generate.py from codegen/data/html-spec.json. Do not edit.
# Source: WHATWG HTML Living Standard, Last Updated 8 September 2026.
"""HTML elements with attribute types derived from the WHATWG HTML Standard."""

from collections.abc import Mapping, Sequence
from typing import Literal, Self, TypedDict, Unpack

from pyhtml.base import AttrValue, Element, VoidElement

type ReferrerPolicy = Literal[
    "",
    "no-referrer",
    "no-referrer-when-downgrade",
    "same-origin",
    "origin",
    "strict-origin",
    "origin-when-cross-origin",
    "strict-origin-when-cross-origin",
    "unsafe-url",
]


class GlobalAttrs(TypedDict, total=False):
    # Keyboard shortcut to activate or focus element [Ordered set of unique space-separated tokens, none of which are identical to another, each consisting of one code point in length]
    accesskey: str | Sequence[str] | None
    # Recommended autocapitalization behavior (for supported input methods) ["on"; "off"; "none"; "sentences"; "words"; "characters"]
    autocapitalize: (
        Literal["on", "off", "none", "sentences", "words", "characters"] | None
    )
    # Recommended autocorrection behavior (for supported input methods) ["on"; "off"; the empty string]
    autocorrect: Literal[True, "on", "off"] | None
    # Automatically focus the element when the page is loaded [Boolean attribute]
    autofocus: bool | None
    # Classes to which the element belongs [Set of space-separated tokens]
    class_: str | Sequence[str] | None
    # Whether the element is editable ["true"; "false"; "plaintext-only"; the empty string]
    contenteditable: Literal[True, "true", "false", "plaintext-only"] | None
    # The text directionality of the element ["ltr"; "rtl"; "auto"]
    dir: Literal["ltr", "rtl", "auto"] | None
    # Whether the element is draggable ["true"; "false"]
    draggable: Literal["true", "false"] | None
    # Hint for selecting an enter key action ["enter"; "done"; "go"; "next"; "previous"; "search"; "send"]
    enterkeyhint: (
        Literal["enter", "done", "go", "next", "previous", "search", "send"] | None
    )
    # Offsets heading levels for descendants [Valid non-negative integer between 0 and 8]
    headingoffset: int | None
    # Prevents a heading offset computation from traversing beyond the element with the attribute [Boolean attribute]
    headingreset: bool | None
    # Whether the element is relevant ["until-found"; "hidden"; the empty string]
    hidden: bool | Literal["until-found", "hidden"] | None
    # The element's ID [Text; see element definition]
    id: str | None
    # Whether the element is inert. [Boolean attribute]
    inert: bool | None
    # Hint for selecting an input modality ["none"; "text"; "tel"; "email"; "url"; "numeric"; "decimal"; "search"]
    inputmode: (
        Literal["none", "text", "tel", "email", "url", "numeric", "decimal", "search"]
        | None
    )
    # Creates a customized built-in element [Valid custom element name of a defined customized built-in element]
    is_: str | None
    # Global identifier for a microdata item [Valid URL potentially surrounded by spaces]
    itemid: str | None
    # Property names of a microdata item [Unordered set of unique space-separated tokens consisting of valid absolute URLs, defined property names, or text; see element definition]
    itemprop: str | Sequence[str] | None
    # Referenced elements [Unordered set of unique space-separated tokens consisting of IDs; see element definition]
    itemref: str | Sequence[str] | None
    # Introduces a microdata item [Boolean attribute]
    itemscope: bool | None
    # Item types of a microdata item [Unordered set of unique space-separated tokens consisting of valid absolute URLs; see element definition]
    itemtype: str | Sequence[str] | None
    # Language of the element [Valid BCP 47 language tag or the empty string]
    lang: str | None
    # Cryptographic nonce used in Content Security Policy checks [CSP] [Text]
    nonce: str | None
    # auxclick event handler [Event handler content attribute]
    onauxclick: str | None
    # beforeinput event handler [Event handler content attribute]
    onbeforeinput: str | None
    # beforematch event handler [Event handler content attribute]
    onbeforematch: str | None
    # beforetoggle event handler [Event handler content attribute]
    onbeforetoggle: str | None
    # blur event handler [Event handler content attribute]
    onblur: str | None
    # cancel event handler [Event handler content attribute]
    oncancel: str | None
    # canplay event handler [Event handler content attribute]
    oncanplay: str | None
    # canplaythrough event handler [Event handler content attribute]
    oncanplaythrough: str | None
    # change event handler [Event handler content attribute]
    onchange: str | None
    # click event handler [Event handler content attribute]
    onclick: str | None
    # close event handler [Event handler content attribute]
    onclose: str | None
    # command event handler [Event handler content attribute]
    oncommand: str | None
    # contextlost event handler [Event handler content attribute]
    oncontextlost: str | None
    # contextmenu event handler [Event handler content attribute]
    oncontextmenu: str | None
    # contextrestored event handler [Event handler content attribute]
    oncontextrestored: str | None
    # copy event handler [Event handler content attribute]
    oncopy: str | None
    # cuechange event handler [Event handler content attribute]
    oncuechange: str | None
    # cut event handler [Event handler content attribute]
    oncut: str | None
    # dblclick event handler [Event handler content attribute]
    ondblclick: str | None
    # drag event handler [Event handler content attribute]
    ondrag: str | None
    # dragend event handler [Event handler content attribute]
    ondragend: str | None
    # dragenter event handler [Event handler content attribute]
    ondragenter: str | None
    # dragleave event handler [Event handler content attribute]
    ondragleave: str | None
    # dragover event handler [Event handler content attribute]
    ondragover: str | None
    # dragstart event handler [Event handler content attribute]
    ondragstart: str | None
    # drop event handler [Event handler content attribute]
    ondrop: str | None
    # durationchange event handler [Event handler content attribute]
    ondurationchange: str | None
    # emptied event handler [Event handler content attribute]
    onemptied: str | None
    # ended event handler [Event handler content attribute]
    onended: str | None
    # error event handler [Event handler content attribute]
    onerror: str | None
    # focus event handler [Event handler content attribute]
    onfocus: str | None
    # formdata event handler [Event handler content attribute]
    onformdata: str | None
    # input event handler [Event handler content attribute]
    oninput: str | None
    # invalid event handler [Event handler content attribute]
    oninvalid: str | None
    # keydown event handler [Event handler content attribute]
    onkeydown: str | None
    # keypress event handler [Event handler content attribute]
    onkeypress: str | None
    # keyup event handler [Event handler content attribute]
    onkeyup: str | None
    # load event handler [Event handler content attribute]
    onload: str | None
    # loadeddata event handler [Event handler content attribute]
    onloadeddata: str | None
    # loadedmetadata event handler [Event handler content attribute]
    onloadedmetadata: str | None
    # loadstart event handler [Event handler content attribute]
    onloadstart: str | None
    # mousedown event handler [Event handler content attribute]
    onmousedown: str | None
    # mouseenter event handler [Event handler content attribute]
    onmouseenter: str | None
    # mouseleave event handler [Event handler content attribute]
    onmouseleave: str | None
    # mousemove event handler [Event handler content attribute]
    onmousemove: str | None
    # mouseout event handler [Event handler content attribute]
    onmouseout: str | None
    # mouseover event handler [Event handler content attribute]
    onmouseover: str | None
    # mouseup event handler [Event handler content attribute]
    onmouseup: str | None
    # paste event handler [Event handler content attribute]
    onpaste: str | None
    # pause event handler [Event handler content attribute]
    onpause: str | None
    # play event handler [Event handler content attribute]
    onplay: str | None
    # playing event handler [Event handler content attribute]
    onplaying: str | None
    # progress event handler [Event handler content attribute]
    onprogress: str | None
    # ratechange event handler [Event handler content attribute]
    onratechange: str | None
    # reset event handler [Event handler content attribute]
    onreset: str | None
    # resize event handler [Event handler content attribute]
    onresize: str | None
    # scroll event handler [Event handler content attribute]
    onscroll: str | None
    # scrollend event handler [Event handler content attribute]
    onscrollend: str | None
    # securitypolicyviolation event handler [Event handler content attribute]
    onsecuritypolicyviolation: str | None
    # seeked event handler [Event handler content attribute]
    onseeked: str | None
    # seeking event handler [Event handler content attribute]
    onseeking: str | None
    # select event handler [Event handler content attribute]
    onselect: str | None
    # slotchange event handler [Event handler content attribute]
    onslotchange: str | None
    # stalled event handler [Event handler content attribute]
    onstalled: str | None
    # submit event handler [Event handler content attribute]
    onsubmit: str | None
    # suspend event handler [Event handler content attribute]
    onsuspend: str | None
    # timeupdate event handler [Event handler content attribute]
    ontimeupdate: str | None
    # toggle event handler [Event handler content attribute]
    ontoggle: str | None
    # volumechange event handler [Event handler content attribute]
    onvolumechange: str | None
    # waiting event handler [Event handler content attribute]
    onwaiting: str | None
    # wheel event handler [Event handler content attribute]
    onwheel: str | None
    # Makes the element a popover element ["auto"; "manual"; "hint"; the empty string]
    popover: Literal[True, "auto", "manual", "hint"] | None
    # The element's desired slot [Text]
    slot: str | None
    # Whether the element is to have its spelling and grammar checked ["true"; "false"; the empty string]
    spellcheck: Literal[True, "true", "false"] | None
    # Presentational and formatting instructions [CSS declarations; see element definition]
    style: str | None
    # Whether the element is focusable and sequentially focusable, and the relative order of the element for the purposes of sequential focus navigation [Valid integer]
    tabindex: int | None
    # Advisory information for the element [Text]
    title: str | None
    # Whether the element is to be translated when the page is localized ["yes"; "no"; the empty string]
    translate: Literal[True, "yes", "no"] | None
    # Whether the element can offer writing suggestions or not. ["true"; "false"; the empty string]
    writingsuggestions: Literal[True, "true", "false"] | None


class AAttrs(GlobalAttrs, total=False):
    # Whether to download the resource instead of navigating to it, and its filename if so [Text]
    download: str | None
    # Address of the hyperlink [Valid URL potentially surrounded by spaces]
    href: str | None
    # Language of the linked resource [Valid BCP 47 language tag]
    hreflang: str | None
    # URLs to ping [Set of space-separated tokens consisting of valid non-empty URLs]
    ping: str | Sequence[str] | None
    # Referrer policy for fetches initiated by the element [Referrer policy]
    referrerpolicy: ReferrerPolicy | None
    # Relationship between the location in the document containing the hyperlink and the destination resource [Unordered set of unique space-separated tokens; see element definition]
    rel: str | Sequence[str] | None
    # Navigable for hyperlink navigation [Valid navigable target name or keyword]
    target: str | None
    # Hint for the type of the referenced resource [Valid MIME type string]
    type: str | None


class A(Element):
    """The <a> element: Hyperlink."""

    __slots__ = ()
    tag = "a"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[AAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


a = A()


class BrAttrs(GlobalAttrs, total=False):
    pass


class Br(VoidElement):
    """The <br> element: Line break, e.g. in poem or postal address."""

    __slots__ = ()
    tag = "br"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[BrAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


br = Br()


class ButtonAttrs(GlobalAttrs, total=False):
    # Indicates to the targeted element which action to take. ["toggle-popover"; "show-popover"; "hide-popover"; "close"; "request-close"; "show-modal"; a custom command keyword]
    command: str | None
    # Targets another element to be invoked. [ID; see element definition]
    commandfor: str | None
    # Whether the form control is disabled [Boolean attribute]
    disabled: bool | None
    # Associates the element with a form element [ID; see element definition]
    form: str | None
    # URL to use for form submission [Valid non-empty URL potentially surrounded by spaces]
    formaction: str | None
    # Entry list encoding type to use for form submission ["application/x-www-form-urlencoded"; "multipart/form-data"; "text/plain"]
    formenctype: (
        Literal[
            "application/x-www-form-urlencoded", "multipart/form-data", "text/plain"
        ]
        | None
    )
    # Variant to use for form submission ["get"; "post"; "dialog"]
    formmethod: Literal["get", "post", "dialog"] | None
    # Bypass form control validation for form submission [Boolean attribute]
    formnovalidate: bool | None
    # Navigable for form submission [Valid navigable target name or keyword]
    formtarget: str | None
    # Name of the element to use for form submission and in the form.elements API [Text; see element definition]
    name: str | None
    # Targets a popover element to toggle, show, or hide [ID; see element definition]
    popovertarget: str | None
    # Indicates whether a targeted popover element is to be toggled, shown, or hidden ["toggle"; "show"; "hide"]
    popovertargetaction: Literal["toggle", "show", "hide"] | None
    # Type of button ["submit"; "reset"; "button"]
    type: Literal["submit", "reset", "button"] | None
    # Value to be used for form submission [Text]
    value: str | None


class Button(Element):
    """The <button> element: Button control."""

    __slots__ = ()
    tag = "button"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[ButtonAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


button = Button()


class DivAttrs(GlobalAttrs, total=False):
    pass


class Div(Element):
    """The <div> element: Generic flow container, or container for name-value groups in dl elements."""

    __slots__ = ()
    tag = "div"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[DivAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


div = Div()


class ImgAttrs(GlobalAttrs, total=False):
    # Replacement text for use when images are not available [Text; see element definition]
    alt: str | None
    # Show user agent controls [Boolean attribute]
    controls: bool | None
    # How the element handles crossorigin requests ["anonymous"; "use-credentials"; the empty string]
    crossorigin: Literal[True, "anonymous", "use-credentials"] | None
    # Decoding hint to use when processing this image for presentation ["sync"; "async"; "auto"]
    decoding: Literal["sync", "async", "auto"] | None
    # Sets the priority for fetches initiated by the element ["auto"; "high"; "low"]
    fetchpriority: Literal["auto", "high", "low"] | None
    # Vertical dimension [Valid non-negative integer]
    height: int | None
    # Whether the image is a server-side image map [Boolean attribute]
    ismap: bool | None
    # Used when determining loading deferral ["lazy"; "eager"]
    loading: Literal["lazy", "eager"] | None
    # Referrer policy for fetches initiated by the element [Referrer policy]
    referrerpolicy: ReferrerPolicy | None
    # Image sizes for different page layouts [Valid source size list]
    sizes: str | None
    # Address of the resource [Valid non-empty URL potentially surrounded by spaces]
    src: str | None
    # Images to use in different situations, e.g., high-resolution displays, small monitors, etc. [Comma-separated list of image candidate strings]
    srcset: str | None
    # Name of image map to use [Valid hash-name reference; see element definition]
    usemap: str | None
    # Horizontal dimension [Valid non-negative integer]
    width: int | None


class Img(VoidElement):
    """The <img> element: Image."""

    __slots__ = ()
    tag = "img"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[ImgAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


img = Img()


class LiAttrs(GlobalAttrs, total=False):
    # Ordinal value of the list item [Valid integer]
    value: int | None


class Li(Element):
    """The <li> element: List item."""

    __slots__ = ()
    tag = "li"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[LiAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


li = Li()


class PAttrs(GlobalAttrs, total=False):
    pass


class P(Element):
    """The <p> element: Paragraph."""

    __slots__ = ()
    tag = "p"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[PAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


p = P()


class SpanAttrs(GlobalAttrs, total=False):
    pass


class Span(Element):
    """The <span> element: Generic phrasing container."""

    __slots__ = ()
    tag = "span"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[SpanAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


span = Span()


class UlAttrs(GlobalAttrs, total=False):
    pass


class Ul(Element):
    """The <ul> element: List."""

    __slots__ = ()
    tag = "ul"

    def __call__(
        self,
        attrs: Mapping[str, AttrValue] | None = None,
        /,
        **kwargs: Unpack[UlAttrs],
    ) -> Self:
        return self._with_attrs(attrs, kwargs)


ul = Ul()

__all__ = [
    "A",
    "AAttrs",
    "Br",
    "BrAttrs",
    "Button",
    "ButtonAttrs",
    "Div",
    "DivAttrs",
    "GlobalAttrs",
    "Img",
    "ImgAttrs",
    "Li",
    "LiAttrs",
    "P",
    "PAttrs",
    "ReferrerPolicy",
    "Span",
    "SpanAttrs",
    "Ul",
    "UlAttrs",
    "a",
    "br",
    "button",
    "div",
    "img",
    "li",
    "p",
    "span",
    "ul",
]
